Repository pycms-nube/Bilibili-SCANA, pull requests merged in 2020-07, with the labels that each got.

#2 第一次代码修正
  __pycache__/api_commit_get.cpython-38.pyc
  __pycache__/dire_manger.cpython-38.pyc
  api-robot.py
  geckodriver.log
Labels: bug

#4 Commit data amalyze module test
  __pycache__/api_commit_get.cpython-38.pyc
  api-robot.py
  api_commit_get.py
  dire_manger.py
  geckodriver.log
Labels: bug, in-progress, test

#7 Smarter and faster robot
  .vscode/settings.json
  __pycache__/api_commit_get.cpython-38.pyc
  __pycache__/error_handel.cpython-38.pyc
  __pycache__/postersql_backend.cpython-38.pyc
  api-robot.py
  api_commit_get.py
  commits_dict.json
  db_test.py
  geckodriver.log
  postersql-backend.py
  postersql_backend.py
  user_dict.json
Labels: in-progress

#9 Time frame mod update
  .gitignore
  __pycache__/api_commit_get.cpython-38.pyc
  api-robot.py
  api_commit_get.py
  postersql_backend.py
Labels: in-progress

#6 A useable database mod
  .gitignore
  api-robot.py
  api_commit_get.py
  postersql_backend.py
Labels: in-progress
